/*
 * This source file was generated by the Gradle 'init' task
 */
package me.dio;

public class Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}
